### ISSUE TITLE
ipaddr.js issue

### ISSUE THREAD

**Issue by 0xkkl** [tomphttp/bare-server-node#21]
Something broke... Error: ipaddr: the address has neither IPv6 nor IPv4 format
    at ipaddr.parse (/node_modules/ipaddr.js/lib/ipaddr.js:929:19)
    at GetAddrInfoReqWrap.callback (/node_modules/@tomphttp/bare-server-node/dist/createServer.js:35:50)
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:131:8)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)

**Comment by e9x** [comment]
This was already fixed in v1.2.6
https://github.com/tomphttp/bare-server-node/releases/tag/v1.2.6
Update your bare server.

**Comment by 0xkkl** [comment]
i did use 1.2.6

**Comment by e9x** [comment]
double check your package.json
