### ISSUE TITLE
gives error even though i did everything

### ISSUE THREAD

**Issue by F1xGOD** [tomphttp/bare-server-node#32]
NotFoundError: Not Found\n    at Server.routeRequest (/opt/render/project/src/node_modules/@tomphttp/bare-server-node/src/BareServer.ts:237:11)\n    at Server.<anonymous> (/opt/render/project/src/node_modules/@tomphttp/bare-server-node/src/cli.ts:106:17)\n    at Server.emit (node:events:518:28)\n    at parserOnIncoming (node:_http_server:1137:12)\n    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)

**Comment by F1xGOD** [comment]
![image](https://github.com/tomphttp/bare-server-node/assets/105874129/3ea61d22-a367-4483-9255-7609b68cc771)
